### ISSUE TITLE
InfluxDB with no data

### ISSUE THREAD

**Issue by gt401** [DigitalShoestringSolutions/HumidityMonitoring#8]
No data seen on InfluxDB dashboard @tobyaharris 

![image](https://github.com/user-attachments/assets/b1a2888b-40e1-4491-89a3-7271bd010bef)

**Comment by Greg-Hawkridge** [comment]
`machine` had a space at the end "Machine_name " which influxdb explorer trimmed but wasn't trimmed in the database. Worked fine in Grafana - not really an issue, but could come up again.
